### ISSUE TITLE
$or nested within $and

### ISSUE THREAD

**Issue by protobi** [davidgtonge/underscore-query#10]
Underscore-query is a great utility, enabling JS objects in MongDB syntax to serve as a nice lingua-franca between MongoDB and Javascript (and via other libraries to SQL as well).  

Ran into a case below which I think should work, but before digging in further wanted to verify whether I'm overlooking something, and possibly get advice on how to extend the code.

There's support for nested $or and $and queries, and the test suite has such an example.  But the following test seems not to yield the expected result:

```js
it("$or nested within $and", function() {
      var a, result;
      a = create();

      var q = {
        $and: [
          { $or: [
                {likes: { $lte: 2}},
                {likes: { $gte: 20}}
            ]
          }
        ]
      }

      result = _.query(a,q);
      assert.equal(result.length, 2);  // fails, returns 0
    });
```

For reference, MongoDB works as expected:

```js
db.query.insert([
    {
      title: "Home",
      colors: ["red", "yellow", "blue"],
      likes: 12,
      featured: true,
      content: "Dummy content about coffeescript"
    }, {
      title: "About",
      colors: ["red"],
      likes: 2,
      featured: true,
      content: "dummy content about javascript"
    }, {
      title: "Contact",
      colors: ["red", "blue"],
      likes: 20,
      content: "Dummy content about PHP"
    }
  ]);

db.query.find({$and: [ $or: [ {likes: { $lte: 2}},  {likes: { $gte: 20}} ] } ]  }).count()

```
yields the result
```js
{ "_id" : ObjectId("54cd39ead8632801eab7e573"), "title" : "About" ,...}
{ "_id" : ObjectId("54cd39ead8632801eab7e574"), "title" : "Contact",... }
```

Am just becoming familiar with coffeescript, so correct me if I'm wrong.  I think MongoDB syntax expects `$and` and `$or` queries to receive arrays of query objects, but the test cases seem to pass hash objects to $and in the nested $and-$or test.

I recognize that this library only aims to support queries that are "MongoDB-like" but if I can reasonably help to handle the range of valid MongoDB queries would love to work on that.

**Comment by davidgtonge** [comment]
Thanks for reporting this. I'll take a look. The library should support mongo style arrays of queries, and also queries as hashes (often easier to read)
