### ISSUE TITLE
Doesn't match when last element of search is within array

### ISSUE THREAD

**Issue by underscoredotspace** [davidgtonge/underscore-query#21]
Both queries work in mongodb, matching the record in `tweet`, but query2 doesn't match in underscore-tweet. I'm guessing because the last element is within an array. 
```js
var query1 = {"user.id_str": "42383066"};
var query2 = {"entities.user_mentions.id_str": "10228272"};

var tweet = [{
	"created_at": "2016-02-20T22:38:54.000Z",
	"id": 701174214930395100,
	"id_str": "701174214930395137",
	"text": "CHVRCHES - Clearest Blue https://t.co/odDPAJU7Bb via @YouTube",
	"user": {
		"id": 42383066,
		"id_str": "42383066",
		"name": "_DotSpace",
		"screen_name": "_DotSpace"
	},
	"entities": {
		"hashtags": [],
		"urls": [{
			"url": "https://t.co/odDPAJU7Bb",
			"expanded_url": "https://youtu.be/BZyzX4c1vIs",
			"display_url": "youtu.be/BZyzX4c1vIs",
			"indices": [25, 48]
		}],
		"user_mentions": [{
			"screen_name": "YouTube",
			"name": "YouTube",
			"id": 10228272,
			"id_str": "10228272",
			"indices": [53, 61]
		}],
		"symbols": []
	}
}];
```

**Comment by underscoredotspace** [comment]
Maybe my query2 shouldn't work? My fix is to use a different query that works on both underscore-query and mongodb: ``{"entities.user_mentions": {$elemMatch: {"id_str": "10228272"}}}``. 

Thanks for the awesome API! Has saved me a heap of time.

**Comment by megawac** [comment]
@underscoredotspace do you know off hand if its supposed to evaluate 1) any of the array items contain a match 2) all contain a match 3) the first item is a match

**Comment by underscoredotspace** [comment]
@megawac so I just ran a quick test and was able to match any item in the array in mongo. probably using more resources in the db however.
