### ISSUE TITLE
$lt null returns true

### ISSUE THREAD

**Issue by KamalAman** [davidgtonge/underscore-query#23]
When querying with $lt or $lte, underscore-query  returns true for null values. 

In javascript:
>var a = {test: null};
a.test < 1 == true, 

However in mongo:
>db.col.insert({"test": null})        
//WriteResult({ "nInserted" : 1 })          
db.col.find({"test": {$lt: 1}}).count()  
//0

**Comment by megawac** [comment]
Interestingly `mongodb` doesn't do this with [`$mod`](https://docs.mongodb.org/manual/reference/operator/query/mod/) and will treat `null` as `0` in this case
