### ISSUE TITLE
Support $regex being defined by string/options

### ISSUE THREAD

**Issue by megawac** [davidgtonge/underscore-query#25]
I'm planning to use $regex to filter a collection on a client and a server. For ease of use transfer (JSON encoding) I wanted to use the `<field>: {$regex: '<str>', $options: '<flags>}` format described here [1]. Underscore-query should construct the regexp in these cases.

[1] https://docs.mongodb.com/manual/reference/operator/query/regex/

**Comment by davidgtonge** [comment]
@megawac here is the functionality in `query-predicate`: https://github.com/davidgtonge/query-predicate/commit/1f0cb8606e14b3eea6d4f3d03f8fcd27a601c259

The code is extreme point-free, but I like the separation of the parser and the query runner.
