### ISSUE TITLE
multiple constraints on the same attribute?

### ISSUE THREAD

**Issue by gradualstudent** [davidgtonge/underscore-query#5]
Should queries handle multiple constraints on the same attribute without using an `$and` query?  For instance, ` {  $gt: 2, $lt: 20  }`.  The suggested test below i think should pass (returning one row), but only one of the constraints appears to apply (thus returning two rows).  

I realize that this specific example (of a range defined by strict inequalities) would be equivalently handled by `$between` but a more general case would allow ranges with a mix of inclusive/exclusive upper/lower bounds like `{$gte: 10, $lt: 20}`, `{$gt: 10, $lte: 20}`, `{$gte: 10, $lte: 20}`, and possibly even additional inequalities, such as `{$gte: 10, $lt: 20, $ne: 13}`.  I believe MongoDB works like this as well.

It seems like this should be handled by the logic for `compoundQuery` in the code, but will need to look closer.

```coffeescript
  it "Handles multiple inequalities", ->
    a = create()
    result = _.query a, likes: {  $gt: 2, $lt: 20  }
    assert.equal result.length, 1
    assert.equal result[0].title, "About"
```

**Comment by davidgtonge** [comment]
Hi, good suggestion. I've added this in. 
Would you be able to help me add a note to the readme via pull request?
