### ISSUE TITLE
$not query syntax

### ISSUE THREAD

**Issue by gradualstudent** [davidgtonge/underscore-query#7]
I like how the $not query syntax allows complex conditions, able to combine constraints on multiple fields.  But just ran into a case where this appears to be different from MongoDB's construction though.  
In Mongo query syntax (http://docs.mongodb.org/manual/reference/operator/query/not/) the $not query is  applied to just the constraint value (e.g. `{likes: {$not: {$lt: 12}}}`) rather than an entire constraint expression (e.g. `{$not: {$likes: {$lt: 12}}}`).   

Would you be open to an extension that works like this?  I think it's possible to allow $not to work in both modes, but would need to verify that more carefully.

```coffeescript
  # This works but is not parallel to MongoDB
  it "$not operator", ->
    a = create()
    result = _.query a, {$not: {likes:  {$lt: 12}}}
    assert.equal result.length, 2
  
  # This is parallel to MongoDB but does not yield expected result
  it "$not operator", ->
    a = create()
    result = _.query a, {likes:  {$not: {$lt: 12}}}
    assert.equal result.length, 2
```

**Comment by davidgtonge** [comment]
Good find - its definitely possible, I'll take a look at it in a bit

**Comment by davidgtonge** [comment]
@gradualstudent I've made a fix for this. Please can you test it and if possible add further test cases for the use of `$or` `$nor`.

Thanks
